### ISSUE TITLE
Decorator\Abstract.class.php

### ISSUE THREAD

**Issue by adrix71** [teodoroleckie/Core#4]
In according with Core\Model\Decorator\Interface.class.php fix the file Core\Model\Decorator\Abstract.class.php to reflect the interface declaration.

In interface the method `decorate()` pass the array $data by reference, in the Abstract.class.php no.

Change the line 33 in Abstract.class.php from

`public function decorate(array $data)`

to

`public function decorate(array &$data)`

----

**Comment by teodoroleckie** [comment]
Fixed
